version: '3.9'
services:
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    api:
        build: .
        ports:
            - 3000:3000
        volumes:
            - .:/chat-api
        depends_on:
            - db
        stdin_open: true
        tty: true